name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: API
        run: pip install --no-cache-dir -r requirements-dev.txt

      - name: Run tests
        working-directory: API
        run: pytest
